import {
    Cartographic,

} from "./CesiumJsInc.js";

function geoReferenced(tileset) {
    if(tileset.asset.extras && tileset.asset.extras.ion && tileset.asset.extras.ion.georeferenced === true) {
        return true;
    }

    // asset.extras.ion property is not available for some tileset generated by RealityCapture.
    let cartographic = Cartographic.fromCartesian(tileset.boundingSphere.center);

    //  Mariana Trench
    if(cartographic.height < -10994)
        return false;

    if(cartographic.height > 8848)
        return false;

    if(cartographic.longitude > CesiumMath.PI || cartographic.longitude < -CesiumMath.PI)
        return false;

    if(cartographic.latitude > CesiumMath.PI_OVER_TWO || cartographic.latitude < -CesiumMath.PI_OVER_TWO)
        return false;

    return true;
}

function disableDefaultScreenSpaceCameraController (scene) {
    // disable the default event handlers

    scene.screenSpaceCameraController.enableRotate = false;
    scene.screenSpaceCameraController.enableTranslate = false;
    scene.screenSpaceCameraController.enableZoom = false;
    scene.screenSpaceCameraController.enableTilt = false;
    scene.screenSpaceCameraController.enableLook = false;
}

function enableDefaultScreenSpaceCameraController (scene) {
    // enable the default event handlers

    scene.screenSpaceCameraController.enableRotate = true;
    scene.screenSpaceCameraController.enableTranslate = true;
    scene.screenSpaceCameraController.enableZoom = true;
    scene.screenSpaceCameraController.enableTilt = true;
    scene.screenSpaceCameraController.enableLook = true;
}

export {
    disableDefaultScreenSpaceCameraController,
    enableDefaultScreenSpaceCameraController,
    geoReferenced
}